extends:
  - google
  - plugin:react/recommended
parser: babel-eslint
plugins:
  - react
rules:
  strict: 0
  require-jsdoc: off
  valid-jsdoc: off
  switch-colon-spacing: 0
  max-len: [error, 120]
  indent:  [error, 2, {"SwitchCase":1}]
  no-invalid-this: off
